# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
    

from PyQt5 import QtCore, QtGui, QtWidgets
from validate_email import validate_email

from loginWindow_02 import *
from methodWindow_04 import *
from main import *



class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 534)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 35);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 200, 291, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n""")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.loginLabel = QtWidgets.QLabel(self.centralwidget)
        self.loginLabel.setGeometry(QtCore.QRect(150, 150, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 290, 121, 51))
        self.pushButton.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.pushButton.setObjectName("pushButton")

        # Quando clica para logar
        # self.pushButton.clicked.connect(self.check) 

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginLabel.setText(_translate("MainWindow", "Insira seu e-mail"))
        self.pushButton.setText(_translate("MainWindow", "OK"))


    def check(self):  
        # print("Check")
        # print(self.lineEdit.text())

        # self.lgnScrn = loginScreen()

        if( validate_email( self.lineEdit.text() )):  
            print("Valid Email")  

            # sys.exit(app.exec_())
            return True
        else:  
            print("Invalid Email") 

    def switchScreen(self):
        print("Troca")

    def openMethodWindow(self):
        # ui2 = methodWindow_03.Ui_Form()
        # # methodWindow_03.Ui_Form().screenPrint()
        # methodWindow_03.Form.show()
        pass



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(MainWindow)



    MainWindow.show()
    sys.exit(app.exec_())


